### ISSUE TITLE
App crashes when adding an event with invalid values

### ISSUE THREAD

**Issue by ther0n** [cs262dFA2018/EventConnect#22]
Currently exceptions are thrown when an event with invalid data is added. These exceptions need to be caught and handled to prevent the app from crashing.

**Comment by OneTrueAsian** [comment]
We need to add a toast yelling at the user. The main issue is when they set the min, forgot what they have to set it to in order to activate the exception.

**Comment by OneTrueAsian** [comment]
Issue has been resolved with adding error marks on the areas where there is issues
